// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Logistics_Transportation
{
    public partial class MLModelPrice
    {
        /// <summary>
        /// model input class for MLModelPrice.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"DistanceKm")]
            public float DistanceKm { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"DurationMin")]
            public float DurationMin { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Weight")]
            public float Weight { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Volume")]
            public float Volume { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"CarType")]
            public string CarType { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Price")]
            public float Price { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModelPrice.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"DistanceKm")]
            public float DistanceKm { get; set; }

            [ColumnName(@"DurationMin")]
            public float DurationMin { get; set; }

            [ColumnName(@"Weight")]
            public float Weight { get; set; }

            [ColumnName(@"Volume")]
            public float Volume { get; set; }

            [ColumnName(@"CarType")]
            public float[] CarType { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLPrice/MLModelPrice.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
